language: objective-c
osx_image: xcode611
before_install:
- scripts/import_keychain.sh
- gem instal xcpretty
- gem install pact-mock_service -v 0.3.0
- gem install cocoapods
- pod update
script: scripts/build.sh
env:
  global:
    secure: l3C+jPG+XT2iBXiz0fjl7UqagwW1RwT5L0BOlGRJKkWaVOA0Z18bi32O7zTko4+P2ecvslla1m92gWvFJxhtLQmv3TcC70YT5koNFE7n0hSD1lGHq31GkMigGg3bFXAKiUC0Q1rSRVfkvMn6bFvtUKN42J1lvd7SE/ziXq2QU1g=
